### ISSUE TITLE
Dev releases

### ISSUE THREAD

**Issue by steve4444** [meganz/MEGAcmd#11]
Today I installed the new version of MEGAcmd. 
I realised that there is no uninstall item in Windows `appwiz.cpl` for MEGAcmd. 

Also it would be nice if you could anticipate the binary release in GitHub, without forcing users to build themselves the dev release. As of of now this is the case of 0.9.7, not yet available from mega.nz.

**Comment by polmr** [comment]
I'm not sure I understood you @steve4444 .... The version available at htts://mega.nz/cmd (0.9.6) comes with an uninstaller. We have discarded the release of 0.9.7 for Windows since we are planning a new release in a few days with several new features. In any case, thanks for the reporting its abscence.

**Comment by steve4444** [comment]
Ok, clear now. In general, confusion arises since on [mega.nz/cmd](https://mega.nz/cmd) page there is no mention of the version and it still links to the meganz/sdk repo. I think you could add a link to [megacmd.changes](https://github.com/meganz/MEGAcmd/blob/master/build/megacmd/megacmd.changes). 

Also note that the NSIS installer is not adding the uninstall entry to Windows appwiz.cpl.
