### ISSUE TITLE
Sync command not working last version

### ISSUE THREAD

**Issue by thelittlefireman** [meganz/MEGAcmd#123]
Hi, since the last version the sync command is not working is always telling me that the folder does not exist and when i show the --help options there is no explication on how to set local and remote folder.

i try to sync my local folder /upload with my remote fodler /Syno-backup

so i use this command : 
```
sync /upload /Syno-backup
sync: error opening '/Syno-backup/': No such file or directory
```
i double check /upload exist on local and /Syno-backup exist on remote

if i use the put command is working

any idea ?

**Comment by polmr** [comment]
Hi there.
That is not an error of MEGAcmd: It comes from your system's `sync` command. 
In order to use "sync" command in non-interactive node, you need to use `mega-sync`. Everything is explained here: https://github.com/meganz/megacmd. We would recommend a careful read of that if you have any doubt.
