### ISSUE TITLE
"Incorrect login" after typing 2FA code

### ISSUE THREAD

**Issue by Simone98RC** [meganz/MEGAcmd#149]
Hi, finally MEGAcmd has been released for Synology Nas: [https://www.synology.com/it-it/dsm/packages/MEGAcmd](url)
I'm running it on [Synology DS116](https://www.synology.com/support/download/DS116) from Windows 10 built-in OpenSSH.
**However** when I login with right credentials and the requested 2FA code, **I get the _Incorrect Login_ error**.

I've attached the log file: [megacmdserver.log](https://github.com/meganz/MEGAcmd/files/2705626/megacmdserver.log)
**Ps ignore the _Login Failed_ related text**, in that occasion I've intentionally wrong to insert my account credentials.

**Comment by flaw** [comment]
Same problem here, 2FA works just fine on the browser but trying it in the interactive mega-cmd on my Synology NAS results in "incorrect authentication".

The only reason I subscribed to MEGA was to establish backups of my NAS and this is proving much more difficult than it really should be.

**Comment by cb-mega** [comment]
Thank you for your feedback! We will have a look into this issue and report back as soon as possible.

**Comment by polmr** [comment]
Hi guys. @Simone98RC  please apologize the sooo late reply. MEGAcmd does not support 2FA in versions prior to 1.0.0. Please ensure MEGAcmd reports the correct version: (`mega-version` or `version` in interactive mode should tell it). If so, a more verbose log will help us identify the issue there. You can obtain it running the server with `mega-cmd-server --debug` or increasing log verbosity before the login attempt with `log DEBUG`. 
Then please send us that megacmdlog.txt file. The log might contain some sensitive data. Feel free to remove anything you don't want to share with us.
If you do not want to post it here (you'd rather not), send it to support@mega.nz and refer this issue in your email so that it can reach development team.

Further info regarding debugging : https://github.com/meganz/MEGAcmd/blob/master/contrib/docs/DEBUG.md

In any case, we plan to release new versions for NAS soon. Please stay tunned!

**Comment by Simone98RC** [comment]
Maybe there was some issue with MEGA server communication, it lasted many months.
However, just now **I've successfully logged in**.

**Comment by sh1boot** [comment]
I have this problem too.  Checking the mega-cmd version I get 1.0.0, so according to this bug _should_ work, but at time of writing 1.0.0 looks _really_ old so I'm guessing it's the same problem all over again.

It seems that DSM 6.2 might be too old to get the latest version of the megacmd package, and that a later version is available for DSM 7.0.

Let's see how a major version upgrade works out for me...
