### ISSUE TITLE
Megacmd backup reaches 100% completed then deletes everything it just transfered

### ISSUE THREAD

**Issue by teknasty** [meganz/MEGAcmd#158]
I'm transferring files from my dedicated server to make backup on the mega cloud, i'm backing up almost 1TB of data so it takes a while and I look at the folders during the process and everything works perfect at least up to 90% was last time i looked, after the backup is done the files on the mega cloud are no longer present and mega reports I have zero usage on the mega server. 

My only guess is that something is wrong with the details of the backup command i used and it's deleting everything it just transferred after it completes. I only want one backup and I do not want it to recur again and nowhere could I see instructions or examples to do this, it seems all the examples assume the user is wanting to make a schedule or multiple backups so this is the command I used to create just one backup transfer of everything and with no schedule for another backup in the future

mega-backup /usr/local/centovacast/var/vhosts/crl/var/spool/media/NewMusicDrive/music /music --period="* * * * * *" --num-backups=1

**Comment by teknasty** [comment]
Here is the folder path it creates on the mega server but after backup completes the sub folders and all files within the bk folder are not here :(   music/music_bk_20190114182139

please help me find away to get this done without it removing my transfer

**Comment by teknasty** [comment]
i just created a test directory on my server and put a few levels of random folders inside and various files within those and ran the same command but made the source path point to the test folder and the backup ran successfully without deleting anything so now i'm really confused why it deletes everything after the real backup completes

**Comment by teknasty** [comment]
i waited to when the mega-backup got to 97% and then i paused the transfer and in my mega account i moved all the successful transfers into a new location, now i'm attempting to setup sync to try and complete the final 3% but it says for status that everything is already synced but perhaps its doing scan currently and won't start the actual sync update process yet until scan completes

I initially tried to do mega copy and also put commands but I kept getting local path is not accessible errors, the mega-backup is the only way so far that i've been successful to have access for transferring things without error

**Comment by polmr** [comment]
bear in mind that synching will exclude some files by default (e.g: those starting by `.`). Also, ensure you have permissions to all the structure you are willing to upload. 
In any case, If you can reproduce the problem with uploading with `mega-put`, it might be interesting to have a log of the server while that happens. In order to do so.
Please, close all megacmd instances and execute the server in a separate console:
Open a console and type
```
killall -2 mega-cmd-server
mega-cmd-server --debug-full | tee megacmd.log
```
Then, open another console and then try to reproduce the issue. Finally quit the server (Ctrl+C in the console that run it should do).
Then please send us that megacmd.log file. The log might contain some sensitive data. Feel free to remove anything you don't want to share with us.
If you do not want to post it here (you'd rather not), send it to support@mega.nz and refer this issue in your email so that it can reach development team.

**Comment by polmr** [comment]
[Available](https://mega.nz/cmd) 1.1.0 version will likely fix this
