### ISSUE TITLE
"user" command  crashes the shell in Windows 

### ISSUE THREAD

**Issue by steve4444** [meganz/MEGAcmd#2]
Just run:

    users -n
 
It freezes. Ctrl-c then kills the shell instead of exiting the command.

**Comment by polmr** [comment]
Hi @steve4444 
I understand it does not crash but hangs. 
"-n" means showing display names. This causes petitions to MEGA servers. It might be stuck due to traffic congestion, a temporary block in your account, ... Also, in such cases, pressing any key might indicate the server to wake up and help reduce the waiting. Still, please be patient. If this is not a temporary issue, it might be interesting to have logs to see what's going on. In order to have them:

Please, close all instances of MEGAcmd, and kill all MEGAcmd processes.
Then open two instances of PowerShell and in the first one execute the server with:
```
$env:PATH += ";$env:LOCALAPPDATA\MEGAcmd"
MEGAcmd.exe --debug-full | tee megacmdserver.log
```

In the second one execute MEGAcmd interactive shell:
```
$env:PATH += ";$env:LOCALAPPDATA\MEGAcmd"
MEGAcmdShell.exe
```
Then try to type your commands and show us what you get in the interactive sell, and send us the server log. The log might contain some sensitive data. If you do not want to post it here, send it to support@mega.nz and refer this issue in your email so that it can reach development team.

**Comment by steve4444** [comment]
I confirm it is just slow. I have some 60 contacts and this might be the cause. I did not realise it, since the plain  `user` command.  without `-n` , is extremely fast.
