### ISSUE TITLE
Difference between "showpcr" in MegaCmd and "View sent request" in the web interface

### ISSUE THREAD

**Issue by steve4444** [meganz/MEGAcmd#3]
`showpcr ` in MegaCmd, after `Outgoing PCRs:`  shows only a subset of the email addresses in "View sent request" in the web interface. Is this by purpose? Shouldn't it be the same? 

`showpcr ` prints both a creation and modification date. What for? And what is the difference? to me they are always the same. 

`showpcr ` prints a number of blanks before and after the email addresses, which makes them inconvenient to parse.  Please, fix it.

Are hidden users from `users -h` the same concept as pending users?

**Comment by polmr** [comment]
1) The list of outgoing PCRs (pending contact requests) should be the same as in the web. Could it be a timing/connectivity issue (either MEGAcmd/web application haven't received the latest changes. Restarting might help in such case)? If restarting the application does not solve it, please do tell us, or better: provide us with logs as indicated in #2.
2) Regarding the creation/modification dates. You can re-send an invitation to a contact (see `-r` option in `invite --help`), as long as a decent time has passed since your last invitation (to avoid SPAM). That is the modification time. In other cases, it should be the same. 
Regarding the number of blanks... this is done for "beautifying" the output. It should be pretty straight to parse it depending on what are you using on top of megacmd (python, powershell, ...). For instance, in powershell you can do sth like:
```
mega-showpcr | ?{$_ -notmatch 'PCRs'} | foreach-object {
  $data = $_ -split " +"
  "{0}" -f $data[1]
}
```
to just get the contact emails.
Finally `users -h` should list actual and former contacts (shown as hidden those who are no longer contacts).

**Comment by steve4444** [comment]
Thanks, things are much more clear now, but let me add the following.     
In scripts, one is mostly interested in processing pending invitations (I mean people invited, who did not yet accepted the invitatons), to decide further actions (share folders, etc.).

To parse the outgoing PCRs I use: 

    $flag=$false
    $pending= & $mega  showpcr | %  { 
        if($flag) { $_.Split("(")[0].Trim()} 
        else {if($_ -eq "Outgoing PCRs:") {$flag=$true}}  
    }


I don't know if this is the best way to do it. However, adding, in the next release, something like:

    showpcr [--in | --out]

would greatly simplify the parsing without great efforts for developers.

**Comment by polmr** [comment]
`showpcr [--in | --out]` .... will do!
