### ISSUE TITLE
Does not work behind proxy

### ISSUE THREAD

**Issue by luismojena** [meganz/MEGAcmd#37]
I have cntlm configured in my local PC linked from my company's proxy, and I have exported http_proxy and https_proxy env vars, both in uppercase and lowercase, but when I do 'login mymail@email.com' and asks for password, it just hangs. 
I look at ~/.megaCmd/megacmdserver.log and I got this:

> [debug: 05:04:10] actUponLogin login
> [debug: 05:04:10] actUponLogin login email: myemail@email.com
> [err: 05:04:10] Failed to Login: Access denied
> [err: 05:04:10] ERROR writing output Code to socket: 32
> [err: 05:04:10] ERROR writing to socket: 32

Can someone please tell me if this is a bug or is intended behavior???

**Comment by polmr** [comment]
That's odd. Maybe a more verbose log could give use some more info
In order to get it, please, close all megacmd instances and execute the server in a separate console:
Open a console and type
```
mega-quit
mega-cmd-server --debug-full | tee megacmd.log
```
Then, open another console and execute mega-cmd interactive shell:
```
mega-cmd
```
Then try to log in normally.
Quit `mega-cmd-server` now (Ctrl+C or typing mega-quit in a third console)

Then please send us that megacmd.log file. The log might contain some sensitive data. Feel free to remove anything you don't want to share with us.
If you do not want to post it here, send it to support@mega.nz and refer this issue in your email so that it can reach development team.
