### ISSUE TITLE
CLI Freezing on "GET"

### ISSUE THREAD

**Issue by sharkeydavid** [meganz/MEGAcmd#462]
Hi,

**System Details:**
  Distro.......: Ubuntu 18.04.5 LTS
  Kernel.......: Linux 4.15.0-124-generic

  Uptime.......: up 8 hours, 29 minutes
  Load.........: 0.16 (1m), 0.10 (5m), 0.06 (15m)
  Processes....: 237 (root), 49 (user), 286 (total)

  CPU..........: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 vCPU)
  Memory.......: 2.4G used, 43G free, 62G total

**MegaCMD Version:**
MEGA CMD> version
MEGAcmd version: 1.1.0: code 1010000

I installed directly from the [source here](https://mega.nz/linux/MEGAsync/xUbuntu_18.04/amd64/) so not sure why it's saying 1.1 when I have installed 1.4.

**Command run:**
`get -m -q "2. Work" '/mnt/sync/2. Work/'`

**Folder Details:**
The folder above is about 730GB. Command runs fine on smaller folders I've tested up to 100GB. Mixture of small and large files - but lots of files/folders overall: 10470 folders & 134257 files.

Any help is appreciated. @polmr I have sent the requested txt files to support@mega.nz from the gdb console although it crashed the mega-cmd-server and I don't think there was anything very useful here from the other issue: #122

**Comment by polmr** [comment]
Hi @sharkeydavid , thanks for taking the time to gather all that information.
I've seen the above mentioned txt's. Those are unexpected
Those indicate that the server is not crashing, but somehow ceases to answer clients petition. You can see it yourself: the gdb run didn't get to crash -> you don't have a prompt to type the `thread apply all bt` command. You could type `Ctrl+C` before inserting that command. That will tell us where the different threads are at that moment, but that's less likely to give us a clue of what is going on (nevertheless, it might, if you want to share that with us )
A few questions:
- When that happens, can you open a system monitor to see if `mega-cmd-server` process CPU/memory are rocketing?
- When that happens, can you open another console and initiate MEGAcmd shell (`mega-cmd`) and execute any command? (`help` or `pwd` will do)
Also, `MEGAcmd version: 1.1.0: code 1010000` is very worrisome, did you install this package: https://mega.nz/linux/MEGAsync/xUbuntu_18.04/amd64/megacmd_1.4.0-6.1_amd64.deb . Note, if you prefer you can download it here: https://mega.nz/cmd. Ensuring you are running 1.4.0 is crucial.
I'm wondering if there was already an older instance of mega-cmd-server running. It shouldn't though: there are checks in place to try and avoid that (and uptime indicates otherwise)
Just to be sure, what are the outputs of these commands:
```dpkg -l | grep megacmd```
```pgrep -l mega-cmd```
Run the later while the issue is happening, please.

**Comment by sharkeydavid** [comment]
Hi @polmr,
That is a strange one. Yes, when i CTRL+C, it clears the screen no problem.

- I have uninstalled and re-installed mega-cmd (from your link) internally in the app it's show v1.1, but the app is clearly v1.4

I re-did the process and the results are:

- Another megacmd shell is opened, it doesnt even open, the banner appears and that is all. (Image attached)

- No crazy CPU usage while the issue is happening - sitting at 0.0% for mega-cmd (images attached)

<img width="898" alt="dpkg" src="https://user-images.githubusercontent.com/19961868/100109497-cd8ad580-2e63-11eb-8993-8677886691d2.png">
<img width="563" alt="installed-version-mega-cmd" src="https://user-images.githubusercontent.com/19961868/100109506-cfed2f80-2e63-11eb-9a8f-d6f0bbf58066.png">
<img width="318" alt="pgrep" src="https://user-images.githubusercontent.com/19961868/100109510-d11e5c80-2e63-11eb-99b4-96edb7568ec6.png">
<img width="593" alt="new-megacmd-shell" src="https://user-images.githubusercontent.com/19961868/100109511-d1b6f300-2e63-11eb-867c-7a2a742b5e46.png">
<img width="877" alt="htop" src="https://user-images.githubusercontent.com/19961868/100109551-dd0a1e80-2e63-11eb-96e2-04070e7b46f4.png">

**Comment by polmr** [comment]
I won't judge ;-P
That makes no sense whatsoever ... Version is hardcoded in the server code. 
It looks as if installation is not overriding the server executable:
```
ps aux | grep mega-cmd-server
```
should tell the executable is /usr/bin/mega-cmd-server
and these are the checksums for Ubuntu 18.04:
```sha256sum /usr/bin/mega-cmd*
c58fb576690e218d4ea5aa828eb7c126b26c99d5f23c2831d07d0e1c54b81c85  /usr/bin/mega-cmd
9fb2001b2512fc5be2d3b4392e658baad3100984f8968baa7753f20dc02e30f1  /usr/bin/mega-cmd-server
```
Would you mind double checking that?

**Comment by sharkeydavid** [comment]
This is very strange, sha256 shows the correct values for both cmd and cmd-server :/

I am not 100% sure what you mean by "It looks as if installation is not overriding the server executable" but below is the output.

I can easily reproduce these errors (have done so on 2x RPi's and some VPS servers) - I'm happy to spin up a VPS and give you SSH access if you want to see yourself and troubleshoot. I'll set it up (assuming I'm doing it right) and you can verify yourself the issue?

<img width="718" alt="Screen Shot 2020-11-28 at 12 58 24" src="https://user-images.githubusercontent.com/19961868/100516157-d1776a00-3179-11eb-9e98-0558b7573187.png">
<img width="606" alt="Screen Shot 2020-11-28 at 12 57 08" src="https://user-images.githubusercontent.com/19961868/100516159-d2a89700-3179-11eb-85b9-54f3e4fe420b.png">

**Comment by sharkeydavid** [comment]
Hi Guys, Just checking in if you have had any luck in pin-pointing the problem? I am sitting on a ton of local data to sync and the manual process would hurt my soul

**Comment by sharkeydavid** [comment]
@polmr any luck mate? My workflow is at a standstill if I can't manage apps using CLI.. Server is sitting idle and very sad
