### ISSUE TITLE
mega-transfers does not return anything Arch

### ISSUE THREAD

**Issue by jmcgrath207** [meganz/MEGAcmd#48]
When I run the mega-transfers command it does not return anything and I tried all the `--help` options. Everything else seems to be working.

**Comment by polmr** [comment]
`mega-transfer` should only output the current active/queue transfers. If the output is empty, it means there is no transfer to show. Bear in mind that completed transfers and transfers related to synching will not be listed by default. You need to pass `--show-completed` and `show-syncs` respectively in order to make them appear.
