### ISSUE TITLE
mega-cmd-server crashes after using 12% of cpu for a while

### ISSUE THREAD

**Issue by douglaslwatts** [meganz/MEGAcmd#492]
On Ubuntu 20.04 with deb package from mega.nz the mega-cmd-server crashes when trying to sync. I can login fine and can initially sync the desired directories, but then when I run mega-sync the mega-cmd-server uses approximately 12% of my cpu power (intel i7-7700k, 4.2GHz x 8) for a while, then it crashes leaving a .crash file in /var/crash. I have tried numerouse things including mega-reload, mega-deleteversions --all and then remove all .debris contents other than tmp/, remove all config files and .debris files and uninstall reinstall, but none of these solve the issue. If I run mega-sync and then ctrl-c before it crashes, then I get a message saying buffer overflow was detected ...clearly that is not good. I have used this to sync my linux machines directories for a long time and this issue started about 6 months ago for no apparent reason. I cannot attach the .crash file, the file type is not supported for upload and if I cp it to a .txt the file is too big.

**Comment by DouglasWatts** [comment]
Since my /home in on a separate drive it is easy for me to reinstall. I did that on both my desktop and laptop, to be sure something I changed in /etc or something was not the issue. megaCMD still crashes every time I use it ...segmentation fault. I install megaSync and that seems to work fine on my desktop, although it crashed with a segmentation fault several times during the initial sync. On my laptop megaSync crashes with segmentation fault every time I boot the machine. Both machines are running Ubuntu 20.04 and I installed the package from mega.nz for my OS. On the laptop megaSync uses 89% or more of the 8GB of memory installed and 20% to 30% of cpu power (i7, not quite as powerful as desktop i7 though). The computer is frozen until megaSync crashes. I guess I need to switch to a different cloud service at this point.

Desktop: Asus motherboard, 16GB DDR4, intel i7-7700k, 4.2GHz x 8, internal graphics only
Laptop:   Asus, 8GB DDR4, 8th gen i7 1.8GHz x 8, nvidea GEFORCE 2GB

**Comment by DouglasWatts** [comment]
It even crashes if sync is paused ...so identical behavior when there is no work to be done

**Comment by aabellagm** [comment]
Hi @DouglasWatts ,

In order to help you, we need some more info like versions, logs and crashes.

**Log:**

To get a log, please ensure the process mega-cmd-server is not running, and run in one terminal :
`mega-cmd-server --debug-full | tee megacmd.log`
Then, open `mega-cmd` in another terminal and run the commands that make it crash.
Colect both the megacmd.log file generated in the first terminal and the commands and it's output from the second terminal.

**Crash:**

1 - install debug symbols
`sudo apt update && sudo apt install megacmd-dbg`

2 - run mega-cmd-server in a debugger (you might need to install gdb)
`gdb mega-cmd-server`
It should say something like:

```
done.
(gdb) 
```

3 - Then run the program (type 'r' + Enter)
Let it run in one terminal and open another one to run the commands that are making the app crash (if any).

4 - Once so, then type in the gdb console: 'thread apply all bt'
Press "Enter" until the output is complete, and

5 - Scroll back and collect the entire output of both terminals

Then please, send us back log and crash text files to our support email support@mega.nz, referring this issue in your email too.

**Comment by DouglasWatts** [comment]
Sorry, I am not ignoring your response. This is my last semester of computer science, so things are starting to pick up. I will do these tests and provide the output as soon as I get a chance. Thank you for your help : )

**Comment by DouglasWatts** [comment]
Sorry, I switched to PCloud a few days before your response to this issue report because I needed to ensure that my machines stay in sync with each other during the semester. So, what I have done to avoid any conflict between the two apps, is create a new user and copy all the directories I was syncing to my Mega to the new user's home. I reinstalled MegaCMD, logged in as the new user, logged into my Mega with that user using MegaCMD, and ran the short script which initiates all of the syncs. This is when the segmentation fault would occur before. It has almost completed syncing all of the directories with the only alarming thing being that it spikes the current cpu core which is handling the process at 98%-100% for extended periods, but temperatures of all cores remain within acceptable range. There has been no segmentation fault as there was before. Before, I had a fresh install of Ubuntu 20.04 on both desktop and laptop and every time I would boot, mega-cmd-server would crash with a segmentation fault within a few minutes having never completed the initial sync. I will rsync the directories which I keep cloud synced to the new user's home every few days and log in as that user to see if the issue occurs again. If I cannot reproduce the issue within a week or so, then I will just close this issue. Perhaps your latest updates have fixed whatever the issue was. Thanks so much for your help, I will do my best to ensure that I am either not experiencing this issue anymore or that I provide you with helpful data for finding the bug if it still exists.

**Comment by aabellagm** [comment]
Hi @DouglasWatts 

Thanks a lot for your info and findings and for reporting the problem.
If you encounter any problems, we will be very pleased to investigate and fix them.

**Comment by douglaslwatts** [comment]
I have had no issue on the new user's account and have started using MegaCMD to sync a few directories on my own `~` and deleted the user I created for testing purposes. the only thing that I notice now is that mega-cmd-server uses around 7%-8% of my laptop's 8GB of RAM and around 2%-3% of my desktop's 16GB of RAM at all times if I keep it running. This is even when all directories are up to date and there is no work to do. I can imagine that it has to take some resources to be constantly watching for changes to sync though. I am closing this issue as I can no longer reproduce the issue. No point having an open issue lying around. If I run into this again, I will be sure to refer to this closed issue and follow your instructions before uninstalling or changing anything. Thanks so much : )
