### ISSUE TITLE
mega-cmd sync behavior

### ISSUE THREAD

**Issue by testcu** [meganz/MEGAcmd#60]
For mega-cmd sync,  From what I observe it is a bi-directional sync with no deletes - only adds. 
 Is this intended behavior of sync?  What command will mirror local to Mega? Thanks

**Comment by polmr** [comment]
"sync" establishes a bidirectional sync between a local and a MEGA folder. The sync engine is the same as in MEGASync (https://mega.nz/sync). Deleting a file/folder in one side should result in the file being deleted* in the other side. 
* actually they are moved to a .debris/Rubbish local folder or SyncDebris in MEGA. See: https://mega.nz/help/client/megasync/general/how-does-syncing-with-mega-work-576c7fae886688e7028b4580 for further info.
If that's not the behavior your are experiencing, something is working unexpectedly. In that case, please try to explain the exact steps you are following, the expected behaviour and the obtained result. Also ensure you have the latests version from https://mega.nz/sync, and indicate what is your OS.

**Comment by testcu** [comment]
Previous used MEGASync successfully for the folder pair. But needed a batch mode so changed to MEGAcmd.  MEGASync no longer used.

Using the latest Windows MEGAcmd download on WIN server 2008r2

 

Example:

before sync

local dir contains files B, C

mega contains files A, B

 

Batch:

exclude files

login

sync local mega

logoout

quit

 

after sync

local dir contains files A, B, C

mega contains files A, B, C

 

No rubbish on Mega

Rubbish on local contains tmp with a lock file of 0 bytes.

 

I was expecting the after sync results to be.

local dir contains files  B, C

mega contains files  B, C

 

Any ideas?

**Comment by polmr** [comment]
Hi @testcu,
that's the expected behavior. That's how the sync engine works. When you first establish a synchronization, it does not know the history that lead to that state (A,B) vs (B,C). It takes the safest approach in order not to unwillingly erase data: it merges the local and remote contents. Once you have a sync established, you can remove a file either local or remotely and the deletion will be propagated to the other location. If you wish to retain the local state (B,C in your case), you'd need to clean the remote folder BEFORE establishing the synchronization, otherwise, it will download the files that don't exist in the local folder (A in this case).
Alternatives:
* If you only wish to have in MEGA what's in your local folder, but you don't want any changes in your local folder. You might be seeking one-way sync (https://en.wikipedia.org/wiki/File_synchronization). Unfortunately, we currently don't support one-way sync as is . But you can always upload a folder to the same location (the parent folder where you want to store it in MEGA): 
```
mega-put C://local/folder /
```
You can execute that as many times as you'd like, It will not re-upload the files that has not been modified: only new files and the modified ones will be uploaded. Notice that when a new version of a file is uploaded the older one will be kept in mega as a version. You can list the versions of a file with `mega-ls --versions`. 
Caveat: local removals won't be propagated in MEGA this way: files will never be delete there using this approach.
* You can use backups: You can configure MEGAcmd to periodically store snapshots of your local folder. See: https://github.com/meganz/MEGAcmd/blob/master/contrib/docs/BACKUPS.md for further info

**Comment by testcu** [comment]
Thank you for your detailed reply!   We need a one-way sync ( mirror local on to Mega). So we restarted the MegaSync (version 3.6.6) and it appears to provide the one-way sync.  Is this what we should expect (that they work differently)?  If so does, MegaSync support a graceful method to stop it from a command line? Or does MegaSync support a method to start/sync/shutdown after 1 cycle?  Thanks

 

.  <https://github.com/notifications/beacon/Amj7FlWzsSi9f8Vkc49sRCZqrjwjvS7Tks5t-17ngaJpZM4UvfUZ.gif>

**Comment by polmr** [comment]
I'm afraid MEGAsync does not provide one-way sync (https://help.mega.nz/megasync/general.html). The sync engine is exactly the same as in MEGAcmd. The thing is... in your case, if you had the synchronization previously configured in MEGAsync, when you restarted it, it might have detected the local deletion of the file C, because it internally knew what the previous state was. (I'm guessing here, don't know what were the steps you followed to have such scenario). MEGAcmd couldn't know what the previous state was, so it decides based on what it finds in local & remote folders. MEGAsync would have done the same had it been configured anew (e.g: logout -> login -> reconfigured syncs).  BTW, I wouldn't recommend having the two (MEGAcmd & MEGAsync) synching the same folder is not something you want to do: the behaviour could be unpredictable.

**Comment by brettneville** [comment]
Is there a way, using mega-cmd, to issue a command in my terminal to delete and/or empty the rubbish bin?

**Comment by polmr** [comment]
You can browse the Rubbish Bin like any folder and delete your files there. `mount` shows its path: `//bin`. If you wish to delete all files within the Rubbish Bin you can do it with:
```
mega-rm -r "//bin/*"
```

**Comment by luganick** [comment]
I found a lot of errors in megacmdserver.log file: "Error creating local directory /foo/bar/.debris" and "Error dispatching transfer. Temporary file not writable: /foo/bar/.getxfer.3333.222.mega". What do that errors mean? My OS is Arch linux and megacmd from AUR. Can you help me?

**Comment by polmr** [comment]
It seems like an issue with permissions / disk full. the line "Error creating local directory"  should say " errno: XXX". That might indicate the actual reason. Please, ensure the user running MEGAcmd has permission rights to the synced folder.

**Comment by luganick** [comment]
Great! Thank you.

**Comment by flesti** [comment]
I have the same problem. Followed the instruction above to delete the remote folder first but still doesn't work. 
If I delete a file locally it doesn't get deleted remotely.

`MEGAcmd version: 1.4.1.0: code 1040100`
on Linux
