### ISSUE TITLE
put command overwrite uploaded files

### ISSUE THREAD

**Issue by Cossey** [meganz/MEGAcmd#611]
I have a situation where I use a running docker container to run megacmd to upload files daily for backing up purposes.

I use the command `put /dbk/special/*.tgz backup/databases/`, however online it shows duplicates of these files every time they are uploaded (ie `razorback_db_daily.tgz` appears multiple times each time this backup is executed). I want the files to be overwritten instead of creating duplicates. Is there a way to do this using the put command?

*I know there is a backup command, but I need something I can easily configure via envvars without having to "stage" the container to backup the files.*

**Comment by polmr** [comment]
Hi Cossey.
Short answer: no, there is no way.
Long answer: there are ways:. FIrst you need to enable versioning in your account, otherwise, duplicates will be created when uploading new files. (you need to open a session in your browser and go to Settings -> File Management -> Enable file versioning). 
With versioning enabled, such command won't create duplicates but a chain of versions of files. 
If you really want to just keep the last copy, you can issue the command:
```
deleteversions backup/databases/*.tgz
```

**Comment by Cossey** [comment]
Thanks @polmr 

This approach will do for now. Closing

**Comment by xeverse** [comment]
even with versioning enabled we
dont see any vesrions in megacmd-ls.
yet can we do it in upload & rename fashion..
