### ISSUE TITLE
sync gets stuck

### ISSUE THREAD

**Issue by srulikuk** [meganz/MEGAcmd#66]
Over the past week i noticed the sync gets stuck, for hours the same download file remain at 0%.
```
root@root:~# mega-transfers --only-downloads --show-syncs 
DIR/SYNC TAG  SOURCEPATH    DESTINYPATH         PROGRESS           STATE
 ⇓ ⇵   79772 /nfs-..._B.jpg /nas0..._B.jpg    0.00% of   62.19 KB  ACTIVE
 ⇓ ⇵   79773 /nfs-..._A.jpg /nas0..._A.jpg    0.00% of  132.99 KB  ACTIVE
 ⇓ ⇵   79774 /nfs-..._B.jpg /nas0..._B.jpg    0.00% of   60.85 KB  ACTIVE
 ⇓ ⇵   79775 /nfs-..._A.jpg /nas0..._A.jpg    0.00% of  130.61 KB  ACTIVE
 ⇓ ⇵   79776 /nfs-..._B.jpg /nas0..._B.jpg    0.00% of   60.33 KB  ACTIVE
 ⇓ ⇵   79777 /nfs-..._A.jpg /nas0..._A.jpg    0.00% of  115.86 KB  ACTIVE
 ⇓ ⇵   79778 /nfs-..._B.jpg /nas0..._B.jpg    0.00% of   59.36 KB  ACTIVE
 ⇓ ⇵   79779 /nfs-..._A.jpg /nas0..._A.jpg    0.00% of  131.13 KB  ACTIVE
 ⇓ ⇵   79780 /nfs-..._B.jpg /nas0..._B.jpg    0.00% of   55.26 KB  ACTIVE
 ⇓ ⇵   79781 /nfs-..._A.jpg /nas0..._A.jpg    0.00% of  136.84 KB  ACTIVE
 ...  Showing first 10 transfers ...
```
In the log file i see
```
[err: 02:38:36] ERROR writing output Code to socket: 32
[err: 02:38:36] ERROR writing to socket: 32
```
After restarting mega-cmd-service it continues to download until the next freeze, what can be causing this?

**Comment by polmr** [comment]
Hi @srulikuk , apologies for the late response. There seems to be an issue with the sync engine being unable to complete a transfer (maybe a file cannot be saved for any partitular reason). I'm afraid the error you've seen in the log is unrelated. We'd need to see a complete log file. If your issue persists, please follow these  instructions for creating a log file so that we can try and analyse what's going on:
Please, close all megacmd instances and execute the server in a separate console:
Open a console and type
```
mega-quit
mega-cmd-server --debug-full | tee megacmd.log
```
Then, open another console and execute mega-cmd interactive shell:
```
mega-cmd
```
Then leave it open for a while (~10 minutes).
Quit mega-cmd-server then (Ctrl+C or typing mega-quit in a third console)

Then please send us that megacmd.log file. The log might contain some sensitive data. Feel free to remove anything you don't want to share with us.
If you do not want to post it here (you'd rather not), send it to support@mega.nz and refer this issue in your email so that it can reach development team.

**Comment by srulikuk** [comment]
It seemed only to happen while there were very large numbers of files to sync (100,000+), after that finished it did not happen again, its been running for the past month without issue.
I think the root of the issue that causes there to be that many files to sync is permissions related, mega-sync does not seem to sync permissions, location 1 (upload location) permissions are nobody:nogroup in location 2 (download location) however they are all root:root (user that starts mega-sync) I changed permissions for all files in location 1 which caused mega to download all location 2 yet the permissions in location 2 did not change, they remain root:root

**Comment by polmr** [comment]
I close the issue then.
You are correct to assume the sync engine does not sync permission. That feature has not been implemented as of now.
