### ISSUE TITLE
FTP Adress - please help (Pro user)

### ISSUE THREAD

**Issue by VictorS47** [meganz/MEGAcmd#728]
Hello,

I just purchased the Pro II plan (8TB) and it's just awesome, exactly what I needed. 

But what I'm wondering now: beside the MEGA iOS app (which works great and its nice), is it possible to obtain a ftp:// adress or something to use in a media player on my iPhone / iPad to stream .avi videos or weirder formats, which the MEGA iOS app doesn't support / play?

I tried already something with the MEGAcmd app, on my Mac...but it's kinda difficult to use. Could anyone help me with this?

I just need a ftp:// adress to add to my iOS video player app.
I really hope it's possible somehow.

I have these options in my media player:
![IMG_1865](https://user-images.githubusercontent.com/116583505/197576519-f18eac44-ea32-4bc8-bfe3-83f8cbe1d4e3.PNG)
![IMG_1864](https://user-images.githubusercontent.com/116583505/197576541-d6f0e7cf-8b02-4503-a59f-03392faacf7f.PNG)

I gave it a try with MEGAcmd...but didn't managed to get any adresses of the main folder of the cloud drive...so pretty please, help. :(

Looking forward for any answer.
Thank you, kindly.

**Comment by VictorS47** [comment]
And just as a additional request, pretty please, if someone (or a dev) gives me some kind of help...don't just give me this tutorial https://github.com/meganz/MEGAcmd/blob/master/contrib/docs/FTP.md ...because I saw it, but I don't understand a few things. How to actually get it to work...the examples there, I find them kinda not clear or easy at all...

Because I paid a lot for my plan, I would kindly ask someone or a dev to **_just give me the command lines_** I need to input into Terminal to get what I need. I'm using **macOS**.

Please, and thank you. (hoping I'll get an answer within 3 months 😩😭☹️😞)

**Comment by VictorS47** [comment]
@polmr help? :(

**Comment by polmr** [comment]
Hi @VictorS47 , 
While I suggest you'd rather go through that docs carefully ...

this may help:
Execute MEGAcmd shell:
```
ftp -d --all  
```
The above will remove any ftp serving
```
ftp / --public
```
This should start serving your Cloud drive 
You should probably rather use a folder within your MEGA cloud.
It will report something like:
```
Serving via ftp Cloud Drive: ftp://127.0.0.1:4990/TArTkKiA/Cloud%20Drive                                                  
```
Caveat: You are making access public, withouth any user/password authentication. Meaning, anyone able to reach your computer's 4990 port, will have access. Plus, you are not configuring FTPS, but FTP, making you far more vulnerable to eavesdroppers. 

Now, you need to actually access it. If your mobile is connected to the same network, you just need to know what is your WLAN IP address, and replace the `127.0.0.1` in the above URL. eg:
```
ftp://198.168.2.127:4990/TArTkKiA/Cloud%20Drive
```
That should be the URL to configure in your client.

Note that MEGAcmd Server needs to be running in your computer in order to for the FTP server to work.

If you want to access from outside your local network, you'd need to configure NAT in your router, and expose your computer 4990 port to the world, and use your public IP (https://www.whatismyip.com/)

**Comment by VictorS47** [comment]
Woah... 😳 I get it now. Thank you for the help and clarifying it for me.
