### ISSUE TITLE
multiple backup process

### ISSUE THREAD

**Issue by sakitA** [meganz/MEGAcmd#80]
Hi. Is it possible that configure multiple backups with mega-backup? When I add the second backup command the previous one is deleted. Is it normal or I do something wrong?

And another problem is when I log out all my backups configuration are removed. How can I keep my backup configuration even I logged out

**Comment by polmr** [comment]
@sakitA Are you trying to have the same local folder in multiple backups? That's the only restriction I can think off. Otherwise, you are allowed to have multiple backups. We might want to add a word about that, or reconsider offering the possibility to have multiple backups of the same local folder ...

Regarding the lost of configuration upon logout. That is intentional. In any case, backups configuration is stored (in linux) at $HOME/.megaCmd/backups. You might want to copy that file elsewhere and restore before login in again.

**Comment by sakitA** [comment]
Yes @polmr you are right I tried to backup the same local folder in multiple backups.  Thanks for lost configuration suggestion. I will do it
