### ISSUE TITLE
Mega is very slow and shows disabled backups when running sync

### ISSUE THREAD

**Issue by johnlabuyfoy1024** [meganz/MEGAcmd#808]
ID                          LOCALPATH             REMOTEPATH       RUN_STATE STATUS ERROR           SIZE     FILES DIRS 

jcd2lU6BvRE          /home/johnf          /Unit3_Backups   Disabled  Synced        NO                3.71 GB  1297  244 

l90bymuKFQQ    /var/www/html        /var/www/html    Disabled  NONE         NO                 73.89 KB 8     2 

T4nGkb5JMFs     /home/johnf             /Unit3_Backups    Disabled  Synced      Local filesystem mismatch 3.71 GB  1297  244 

_wOcSxjgn0U    /home/johnf              /Unit4_Backups    Running   Synced      NO                13.56 GB 97816 19633

**Comment by polmr** [comment]
What version of MEGAcmd are you running?

Please, ensure you are running the last version of MEGAcmd from https://mega.io/cmd

The above lists shows 4 syncs, but only the last one is enabled, seemingly fine (status means that it is up-to-date).

You may want to reenable or remove and configure new ones for them to work. More info with `sync --help`

Slowness can be due to a huge range of factors:
- bandwidth limitations
- scanning local files taking long
- ever changing files may penalize throughput. You may want to consider synching selective folders within your $HOME, rather than it entirely.
- competing sync engine (other syncing software, MEGAsync, ...) may create loops in the sync engine

**Comment by johnlabuyfoy1024** [comment]
Thanks - i've resolved this issue by using sync -d to remove the disabled syncs and upgrading megasync and megacmd on my Ubuntu servers.
