### ISSUE TITLE
IP address for Mega?

### ISSUE THREAD

**Issue by sislane** [meganz/MEGAcmd#873]
IP address for Mega?
![image](https://github.com/meganz/MEGAcmd/assets/139064220/ea1d314d-9448-402c-8f8c-c54da78bc9cd)

**Comment by polmr** [comment]
MEGA has no public IP address serving a FTP Server.

You can, however, use MEGAcmd to instantiate an FTP Server in your computer. The IP address then, would be the IP of your computer. If you need to access from outside your LAN, then the IP would be your public IP, but you'd need to configure NATing of the served port.
Note: you'd need to pass `--public` to your FTP command in order to access it from somewhere else other than your computer.

**Comment by sislane** [comment]
> MEGA has no public IP address serving a FTP Server.
> 
> You can, however, use MEGAcmd to instantiate an FTP Server in your computer. The IP address then, would be the IP of your computer. If you need to access from outside your LAN, then the IP would be your public IP, but you'd need to configure NATing of the served port. Note: you'd need to pass `--public` to your FTP command in order to access it from somewhere else other than your computer.

I see, I suspected this. Thank you.
